// Generated by gencpp from file turtlesim_controller/HarmonicResponse.msg
// DO NOT EDIT!


#ifndef TURTLESIM_CONTROLLER_MESSAGE_HARMONICRESPONSE_H
#define TURTLESIM_CONTROLLER_MESSAGE_HARMONICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_controller
{
template <class ContainerAllocator>
struct HarmonicResponse_
{
  typedef HarmonicResponse_<ContainerAllocator> Type;

  HarmonicResponse_()
    : vel(0.0)  {
    }
  HarmonicResponse_(const ContainerAllocator& _alloc)
    : vel(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HarmonicResponse_

typedef ::turtlesim_controller::HarmonicResponse_<std::allocator<void> > HarmonicResponse;

typedef boost::shared_ptr< ::turtlesim_controller::HarmonicResponse > HarmonicResponsePtr;
typedef boost::shared_ptr< ::turtlesim_controller::HarmonicResponse const> HarmonicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator1> & lhs, const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator2> & rhs)
{
  return lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator1> & lhs, const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "378ca590f55ecb8d30867c8ddf1db3c5";
  }

  static const char* value(const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x378ca590f55ecb8dULL;
  static const uint64_t static_value2 = 0x30867c8ddf1db3c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_controller/HarmonicResponse";
  }

  static const char* value(const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel\n"
"\n"
;
  }

  static const char* value(const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HarmonicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_controller::HarmonicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_controller::HarmonicResponse_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_CONTROLLER_MESSAGE_HARMONICRESPONSE_H
