// Generated by gencpp from file turtlesim_controller/Velocity.msg
// DO NOT EDIT!


#ifndef TURTLESIM_CONTROLLER_MESSAGE_VELOCITY_H
#define TURTLESIM_CONTROLLER_MESSAGE_VELOCITY_H

#include <ros/service_traits.h>


#include <turtlesim_controller/VelocityRequest.h>
#include <turtlesim_controller/VelocityResponse.h>


namespace turtlesim_controller
{

struct Velocity
{

typedef VelocityRequest Request;
typedef VelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Velocity
} // namespace turtlesim_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim_controller::Velocity > {
  static const char* value()
  {
    return "9a5456fb608aa5d493111238fa8d046f";
  }

  static const char* value(const ::turtlesim_controller::Velocity&) { return value(); }
};

template<>
struct DataType< ::turtlesim_controller::Velocity > {
  static const char* value()
  {
    return "turtlesim_controller/Velocity";
  }

  static const char* value(const ::turtlesim_controller::Velocity&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim_controller::VelocityRequest> should match
// service_traits::MD5Sum< ::turtlesim_controller::Velocity >
template<>
struct MD5Sum< ::turtlesim_controller::VelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_controller::Velocity >::value();
  }
  static const char* value(const ::turtlesim_controller::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_controller::VelocityRequest> should match
// service_traits::DataType< ::turtlesim_controller::Velocity >
template<>
struct DataType< ::turtlesim_controller::VelocityRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim_controller::Velocity >::value();
  }
  static const char* value(const ::turtlesim_controller::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim_controller::VelocityResponse> should match
// service_traits::MD5Sum< ::turtlesim_controller::Velocity >
template<>
struct MD5Sum< ::turtlesim_controller::VelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_controller::Velocity >::value();
  }
  static const char* value(const ::turtlesim_controller::VelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_controller::VelocityResponse> should match
// service_traits::DataType< ::turtlesim_controller::Velocity >
template<>
struct DataType< ::turtlesim_controller::VelocityResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim_controller::Velocity >::value();
  }
  static const char* value(const ::turtlesim_controller::VelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_CONTROLLER_MESSAGE_VELOCITY_H
