// Generated by gencpp from file turtlesim_controller/HarmonicRequest.msg
// DO NOT EDIT!


#ifndef TURTLESIM_CONTROLLER_MESSAGE_HARMONICREQUEST_H
#define TURTLESIM_CONTROLLER_MESSAGE_HARMONICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_controller
{
template <class ContainerAllocator>
struct HarmonicRequest_
{
  typedef HarmonicRequest_<ContainerAllocator> Type;

  HarmonicRequest_()
    : x(0.0)  {
    }
  HarmonicRequest_(const ContainerAllocator& _alloc)
    : x(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HarmonicRequest_

typedef ::turtlesim_controller::HarmonicRequest_<std::allocator<void> > HarmonicRequest;

typedef boost::shared_ptr< ::turtlesim_controller::HarmonicRequest > HarmonicRequestPtr;
typedef boost::shared_ptr< ::turtlesim_controller::HarmonicRequest const> HarmonicRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator1> & lhs, const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator1> & lhs, const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlesim_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abd5d1e9c3ac157a0df3ba27b65d3384";
  }

  static const char* value(const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabd5d1e9c3ac157aULL;
  static const uint64_t static_value2 = 0x0df3ba27b65d3384ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_controller/HarmonicRequest";
  }

  static const char* value(const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
;
  }

  static const char* value(const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HarmonicRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_controller::HarmonicRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_controller::HarmonicRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_CONTROLLER_MESSAGE_HARMONICREQUEST_H
